export default {
  SAVE_CODE: 'SAVE_CODE',
  CHANGE_FONT_SIZE: 'CHANGE_FONT_SIZE',
  CHANGE_THEME: 'CHANGE_THEME',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  SIGN_IN: 'SIGN_IN',
  TOGGLE_MENU: 'TOGGLE_MENU',
  SAVE_EVAL: 'SAVE_EVAL',
  LOG_OUT: 'LOG_OUT'
};
